travel_advisor_homepage:
    path:     /
    defaults: { _controller: TravelAdvisorBundle:Page:index }

travel_advisor_voyage:
    path:     /voyage
    defaults: { _controller: TravelAdvisorBundle:Page:voyage }

#Route affichant la vue prenant en compte le prénom dans l'URL
#travel_advisor_voyageP:
#    path:     /voyage/{votreprenom}
#    defaults: { _controller: TravelAdvisorBundle:Page:voyageP }
#    requirements:
#        _method: GET

travel_advisor_voyageP:
    path:     /voyage/{votreprenom}
    defaults: { _controller: TravelAdvisorBundle:Page:voyage }
    requirements:
        _method: GET

travel_advisor_admin:
    path:     /admin/
    defaults: { _controller: TravelAdvisorBundle:Admin:index }


